name: popsicle_sales_manager_client
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  select_form_field: ^2.2.0
  d_chart: ^2.2.11
  shared_preferences: ^2.1.0
  art_sweetalert: ^0.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.13.0"

flutter_icons:
  android: 'launcher_icon'
  image_path: 'assets/icons/popsicle.png'
  min_sdk_android: 21


flutter:
  uses-material-design: true
  
  assets:
    - assets/fonts/
    - assets/images/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-Semibold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700